In [2]:
import numpy as np

In [4]:
data1 = [6,7.5,8,0,1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [5]:
arr2 = np.array([[1,2,3], [4,5,6]])
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
arr1.dtype

dtype('float64')

In [7]:
arr2.ndim

2

Placeholder Functions

In [8]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [9]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [11]:
arng = np.arange(0,10,2)
arng

array([0, 2, 4, 6, 8])

Recasting

In [12]:
arr = np.array([1,2,3,5,4])
arr.dtype

dtype('int64')

In [14]:
arr_i32 = arr.astype('int32')
arr_i32

array([1, 2, 3, 5, 4], dtype=int32)

In [16]:
arr_f64 = arr_i32.astype(np.float64)
arr_f64

array([1., 2., 3., 5., 4.])

Inspection


In [20]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [21]:
a.shape

(3, 4)

In [22]:
a.ndim

2

In [23]:
a.size

12

In [24]:
len(a)

3

Random Seed and Random Functions

In [28]:
# legacy global seed
np.random.seed(42)
legacy_sample = np.random.randn(3)
legacy_sample

array([ 0.49671415, -0.1382643 ,  0.64768854])

In [ ]:
# modern generator
rng = np.random.default_rng(42)
norm = rng.normal(loc = 0, scale = 1, size =(2,3))
norm

array([[ 0.30471708, -1.03998411,  0.7504512 ],
       [ 0.94056472, -1.95103519, -1.30217951]])

In [32]:
uniform = rng.uniform(low=1, high=1, size=(2,3))
uniform

array([[1., 1., 1.],
       [1., 1., 1.]])

In [34]:
integers = rng.integers(0,10, size=5)
integers

array([7, 6, 4, 8, 5])

Array Functions

In [38]:
x = np.array([-4,-1,0,1,4],dtype=float)
x

array([-4., -1.,  0.,  1.,  4.])

In [39]:
x = np.array([-4,-1,0,1,4],dtype=float)
y = np.array([10,20,30,40,50], dtype=float)

In [40]:
# unary single-array operations
np.abs(x)

array([4., 1., 0., 1., 4.])

In [41]:
np.sqrt(np.abs(x))

array([2., 1., 0., 1., 2.])

In [42]:
# binary (multi-array) operations --> vectorized
np.add(x,y)


array([ 6., 19., 30., 41., 54.])

In [43]:
np.multiply(x,y)

array([-40., -20.,   0.,  40., 200.])

In [44]:
np.power(x,2)

array([16.,  1.,  0.,  1., 16.])

Conditional where statement

In [46]:
arr = np.arange(-3,4)
arr

array([-3, -2, -1,  0,  1,  2,  3])

In [47]:
labels = np.where(arr>=0, "nonnegative", "negative")
labels

array(['negative', 'negative', 'negative', 'nonnegative', 'nonnegative',
       'nonnegative', 'nonnegative'], dtype='<U11')

In [48]:
# replace negative with a 0 for isntance
arr_nonneg = np.where(arr<0, 0, arr)
arr_nonneg

array([0, 0, 0, 0, 1, 2, 3])

Aggregate Functions

In [50]:
b = np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
b.sum()

np.int64(78)

In [52]:
b.mean()

np.float64(6.5)

In [53]:
b.std()

np.float64(3.452052529534663)

In [54]:
b.sum(axis=0)

array([15, 18, 21, 24])

In [55]:
b.sum(axis=1)

array([10, 26, 42])

Sorting and Unique

In [60]:
d = np.array([3,1,2,3,5,1,4])
d

array([3, 1, 2, 3, 5, 1, 4])

In [61]:
np.sort(d)

array([1, 1, 2, 3, 3, 4, 5])

In [63]:
np.argsort(d)

array([1, 5, 2, 0, 3, 6, 4])

In [64]:
np.unique(d)

array([1, 2, 3, 4, 5])

Indexing and Slicing

In [67]:
na = np.arange(12)
na_slice = na[5:8]
na_slice

array([5, 6, 7])

In [69]:
na_slice[:] = 12
na_slice

array([12, 12, 12])

In [70]:
na

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9, 10, 11])

In [71]:
# multidimensial indexing
m = np.arange(1,13).reshape(3,4)
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [72]:
# row 1, col 2
m[1,2]

np.int64(7)

In [73]:
# rows 0-2 and columns 1-3
m[0:2, 1:3]

array([[2, 3],
       [6, 7]])

In [74]:
# first column
m[:,0]

array([1, 5, 9])

In [75]:
# every other row
m[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

Boolean Indexing

In [76]:
scores = np.array([88, 92, 67, 73, 95, 81, 60])
passed = scores >= 70

In [77]:
passed

array([ True,  True, False,  True,  True,  True, False])

In [78]:
# set all failing scores <70 to 70
scores2 = scores.copy()

In [79]:
scores2[scores2 < 70] = 70
print("curves applied: ", scores2)

curves applied:  [88 92 70 73 95 81 70]


Code Challenge

In [57]:
import numpy as np

# 1. create a 5x4 NumPy array
data1 = np.random.rand(5, 4)   # 5 rows, 4 columns with random values [0,1)

print("Data1:\n", data1)

# 2. the numbers are already from a uniform distribution [0,1)
# (np.random.rand generates uniform random numbers)

# 3. sum, average, std, variance
print("\nSum:", np.sum(data1))
print("Average:", np.mean(data1))
print("Standard Deviation:", np.std(data1))
print("Variance:", np.var(data1))

# 4. create an object with 1s and 0s based on condition
binary_data = np.where(data1 >= 0.5, 1, 0)
print("\nBinary Data:\n", binary_data)


Data1:
 [[0.58779155 0.06309849 0.49710274 0.92839462]
 [0.80603084 0.19839124 0.34528354 0.53473647]
 [0.97858347 0.5030445  0.3474475  0.21278653]
 [0.17745402 0.1040286  0.18745545 0.04031375]
 [0.23991727 0.5462427  0.20778317 0.99270398]]

Sum: 8.49859045227224
Average: 0.42492952261361194
Standard Deviation: 0.2984748713954923
Variance: 0.08908724885455566

Binary Data:
 [[1 0 0 1]
 [1 0 0 1]
 [1 1 0 0]
 [0 0 0 0]
 [0 1 0 1]]


Code Challenge

In [35]:
np.random.seed(89)

In [37]:
# create a random generator with a specific state
rng = np.random.RandomState(12345)

# binomial distribution: n=10 trials, p=0.5 probability, shape=3x3x3
binomial_array = rng.binomial(n=10, p=0.5, size=(3, 3, 3))
binomial_array


array([[[7, 4, 4],
        [4, 5, 5],
        [8, 6, 6]],

       [[6, 6, 8],
        [1, 3, 4],
        [6, 6, 7]],

       [[8, 6, 6],
        [6, 5, 4],
        [5, 6, 9]]], dtype=int32)

Code Challenge

In [58]:
import numpy as np

# create a NumPy array with 20 numbers
arr = np.arange(1, 21)   # array([ 1,  2,  3, ..., 20])

# slice items 11-14 (note: Python uses 0-based indexing, so these are indices 10:14)
arrslice = arr[10:14]

# change all items in the slice to 2021
arrslice[:] = 2021

# print original array
print("Original array:\n", arr)

# did the original list change?
print("\nSliced array:\n", arrslice)


Original array:
 [   1    2    3    4    5    6    7    8    9   10 2021 2021 2021 2021
   15   16   17   18   19   20]

Sliced array:
 [2021 2021 2021 2021]
